apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations: {}
  name: incloud-k8s-role-graph
  namespace: argocd
spec:
  destination:
    namespace: incloud-k8s-role-graph
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: registry-1.docker.io/prorobotech
    chart: k8s-role-graph
    targetRevision: 0.1.0-8da6093
    helm:
      values: |-
        server:
          image:
            tag: "CLOUD-514-5fb1cc6e"
        web:
          image:
            tag: "CLOUD-514-5fb1cc6e"
        expose:
          enabled: false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
