apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations: {}
  name: incloud-k8s-role-graph
  namespace: argocd
spec:
  destination:
    namespace: incloud-k8s-role-graph
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: oci://registry-1.docker.io/prorobotech/k8s-role-graph
    chart: k8s-role-graph
    targetRevision: 0.1.0-dc97fbc
    helm:
      values: |-
        server:
          image:
            tag: "release-0.1.0-2d3990b1"
        web:
          image:
            tag: "release-0.1.0-2d3990b1"
        expose:
          enabled: false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
